# Generated by Django 4.2.6 on 2023-11-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('imagage', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='brands_products', to='app.products')),
            ],
        ),
    ]
