# Generated by Django 4.2.6 on 2023-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
