# Generated by Django 4.2.6 on 2023-11-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_brands_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='imagage',
            new_name='image',
        ),
    ]
