# Generated by Django 4.2.6 on 2023-12-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_banners_alter_sizeproduct_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
